version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: car-rental-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-car-rental:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d car_rental"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data-car-rental: